### ISSUE TITLE
Como usar markdown nas issues?  😄

### ISSUE THREAD

**Issue by joao-invernal** [Mr-Sena/turma12java#2]
# Use # no inicio da linha parar criar um cabeçalho com essa formatação

- Use - no começo da linha para pautar nesse formato

**Comment by Mr-Sena** [comment]
#3 @Mr-Sena

**Comment by joao-invernal** [comment]
#4  - Primeiro pull request executado...

**Comment by joao-invernal** [comment]
---
# João
Lista numerada:

1. One
2. Two
3. Three

Lista demarcada:
* Serve tanto com astéristico
- Quanto com traço
- Porém nesse caso cria uma outra lista
- Perçeba a diferença do espaçamento entre o primeiro item e o item dois

Lista de Tarefas:
- [ ] Tomar banho
- [x] Assistir as aulas de markdown

---
## Tabela

N. | Nome | Nota
---|---|---
1 | José | 10
2 | João | 7
3 | Augusto | 8

Código de honra: `while True:
    return "Ao infinito e além..."
`

😄 


![ihowToDo](https://user-images.githubusercontent.com/69920763/113524274-15dda100-9584-11eb-97f4-83ae58800373.png)
[](url)

**Comment by joao-invernal** [comment]
> #4 - Primeiro pull request executado...

Congratulatiions
